model:
  id: "bigcode/starcoder2-7b"
  max_seq_length: 512

data:
  path: "data/train.json"
  response_template: "\n### Response:"


peft:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  use_dora: True

trainer:
  output_dir: "models/astra-coder-v1-lightning-adapter"
  num_train_epochs: 5
  batch_size: 16
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  accelerator: "gpu"
  devices: [0,1]
  precision: "bf16-mixed"
  logging_steps: 50

wandb:
  project: "Astra-Coder"
  name: "astra-coder-v1-finetune"
  entity: null
