leaseed: 42

model:
  id: "bigcode/starcoder2-7b"
  max_seq_length: 512

data:
  train_path: "data/train_dataset.json"
  val_path: "data/val_dataset.json"
  response_template: "\n### Response:"


peft:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  #use_dora: True

trainer:
  output_dir: "models/astra-coder-v1-lightning-adapter"
  num_train_epochs: 200
  batch_size: 16
  per_device_train_batch_size: 2
  per_device_val_batch_size: 2
  gradient_accumulation_steps: 8
  precision: "bf16-mixed"
  logging_steps: 1
  accelerator: "gpu"
  strategy: "ddp"
  devices: [0]
  val_check_interval: 1.0

early_stopping:
  monitor: "val_em_accuracy"
  patience: 5
  mode: "max"

optimizer:
  learning_rate: 5e-5 
  weight_decay: 0.01

logger:
  wandb:
    _target_: lightning.pytorch.loggers.WandbLogger
    project: "Astra-Coder"
    name: "starcoder2-7b-lora-finetune"
    entity: "BrainLoop"
    log_model: false